version: '1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - D:/project/project-board/mysql:/var/lib/mysql
    cpus: 0.5
    mem_limit: "8g"